### ISSUE TITLE
Onboarding PR resets renovate.json

### ISSUE THREAD

**Issue by hkdobrev** [renovateapp/renovate#1360]
I couldn't find a similar issue opened for that earlier, but it's really annoying.

The initial onboarding PR contains the following in `renovate.json`:
```json
{
  "extends": [
    "config:base"
  ]
}
```

I change it to something like this (again in `renovate.json`, I don't use `package.json` `renovate` field):
```json
{
  "branchPrefix": "renovate-",
  "extends": [
    "config:base",
    ":preserveSemverRanges",
    ":semanticCommitsDisabled"
  ],
  "labels": ["devops"],
  "multipleMajorPrs": true,
  "reviewers": ["..."]
}
```

However, after a few hours, the PR is force-pushed by the renovate bot to the original `renovate.json` and the PR description is again listing pinning dependencies which I don't want from the start.

I thought I was mistaken, but it happened for the 2nd time in the span of 24 hours. I've checked the Slack logs from GitHub and it shows the renovate bot is force-pushing the branch after my changes. 

I've tried both adding new commits to the `renovate/config` branch and squashing changes to the original. Updating the PR description works, but after a few hours, everything is being reset.

**Comment by rarkins** [comment]
Sorry, I think it’s only impacting if you have branchPrefix customised. I fixed another problem with that in onboarding this week but appear to have caused this new one. Should be fixable today.

**Comment by hkdobrev** [comment]
Thank you! 🙏

**Comment by rarkins** [comment]
FYI it should be fixed now (https://github.com/renovateapp/renovate/commit/228b823e45febed8d8ad09479ed832511adca13a) however I haven't had the chance to verify it myself today by testing it against the bot, so I haven't closed this issue yet.

**Comment by hkdobrev** [comment]
Thanks! I've updated the `renovate.json` file once again with `branchPrefix` inside. I'll close the issue tomorrow if it hasn't been reset.

**Comment by rarkins** [comment]
Sounds good. I just checked logs and - as it should - it seems like it ran on that repository already once you made the update.

**Comment by ajafff** [comment]
@rarkins this is still an issue for me in https://github.com/fimbullinter/wotan/pull/87. It keeps resetting `renovate.json`.

I don't have a custom `branchPrefix` in my config.

**Comment by rarkins** [comment]
Damn, sorry. I added a feature yesterday to allow self-hosted users to have custom onboarding defaults and it may have caused this reversion.
