### ISSUE TITLE
PR Titles appearing with {{depName}}

### ISSUE THREAD

**Issue by adam-moss** [renovateapp/renovate#1652]
#### This is a:

* [X] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [X] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
Hi,

Over the past couple of days I've started to get PR Titles appearing like:

`refactor({{depName}}): pin dependency jquery-browser to v1.7.2-3`

The commit itself however is correctly appearing as:

`refactor(jquery-browser): pin dependency version`

I think this is related to:
https://github.com/renovateapp/renovate/pull/1637

Is this the future direction for Renovate?

Cheers

**Comment by rarkins** [comment]
@adam-moss sorry for the inconvenience. I've pushed a quick fix now that should solve the PR Title display problem, we should see a message here once it's released to npm and after that Docker Hub will begin building.

I do plan to simplify soon how templating for PR titles and commit messages works, so that so much duplication is not necessary. I'm yet to decide whether to consider it breaking or not, because existing template overrides should still continue working even though overriding the whole template will no longer be recommended.

**Comment by adam-moss** [comment]
Thanks for the quick response on that.

It is an interesting one re breaking, I don't actually override the PR title other than by virtue of the semantic commit scope and type, the only changes are to the commit message itself.

I think there is a further issue with titles unrelated to this when pinning docker digests though - the title just ends with `v` and no version (sha in this case). Will do some more digging and raise an issue/pr if I find anything of substance.

Cheers

**Comment by rarkins** [comment]
If you're only adjusting the semantic scope/type then actually you would have nothing to worry about or pay attention to. Some people copy/paste the entire `prTitle` template (including all the `{{#if foo}}` etc) just to change something small, and I hope to invent a kind of "meta" template to avoid that, e.g. like `{{prefix}}{{action}}{{topic}}{{qualifier}}{{suffix}}` and catch everyone's use cases within that.

**Comment by rarkins** [comment]
> I think there is a further issue with titles unrelated to this when pinning docker digests though - the title just ends with v and no version (sha in this case). Will do some more digging and raise an issue/pr if I find anything of substance.

It's quite possible as with today's setup as there's so much copy/paste between different managers (npm, docker, node, etc) and PR types (pin, digest, major, minor, rollback, etc). Please raise an issue if you can reproduce.

**Comment by mikeshawdev** [comment]
@rarkins it seems that we're still seeing this issue on our projects, with `{{depName}}` in the PR title. I'm using the same system as @adam-moss

**Comment by rarkins** [comment]
@mikeshawdev sorry about that - I'll take another look. Can you share again the relevant config so that I can try to replicate it on my end?

**Comment by mikeshawdev** [comment]
```
module.exports = {
    autodiscover: true,
    automerge: false,
    branchPrefix: 'chore/',
    commitBody: 'Signed-off-by: {{{gitAuthor}}}',
    commitMessage: '{{semanticPrefix}} update to {{newVersion}}',
    docker: {
        enabled: true,
        pin: {
            branchPrefix: 'refactor/',
            commitMessage: '{{semanticPrefix}} pin image digest',
            semanticCommitType: 'refactor',
            semanticCommitScope: '{{depName}}',
        }
    },
    onboarding: false,
    pin: {
        branchPrefix: 'refactor/',
        commitMessage: '{{semanticPrefix}} pin dependency version',
        semanticCommitType: 'refactor',
        semanticCommitScope: '{{depName}}'
    },
    pinDigests: true,
    pinVersions: true,
    platform: 'gitlab',
    prCreation: 'immediate',
    prHourlyLimit: 3,
    rebaseStalePrs: true,
    semanticCommits: true,
    semanticCommitType: 'chore',
    semanticCommitScope: '{{depName}}',
    timezone: 'Europe/London'
}
```

**Comment by adam-moss** [comment]
Hi @rarkins, sorry to be a pita but could you let me know when this change will hit your official docker image?

**Comment by rarkins** [comment]
Docker Hub is configured to autobuild every semver tag it sees so should usually be available within 30 minutes of an npm release

**Comment by adam-moss** [comment]
Yeah I thought so, but doesn't look like it unless there is something weird happening here in the snowy UK:

```sh
# docker pull renovate/renovate:latest
latest: Pulling from renovate/renovate
605ce1bd3f31: Pull complete 
9d1b67fd48b4: Pull complete 
84281a4e5312: Pull complete 
86a99c15751b: Pull complete 
70243572e908: Pull complete 
9ed02372304a: Pull complete 
324248764162: Pull complete 
abf043f3579e: Pull complete 
f685fe5b80e1: Pull complete 
6ed3a387df31: Pull complete 
Digest: sha256:d9b97290b21b51275fc284c3bfd782746465a327d1928358ca210943d41b695b
Status: Downloaded newer image for renovate/renovate:latest
```

```sh
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
renovate/renovate   latest              94b454eed57e        42 hours ago        292MB
```

**Comment by rarkins** [comment]
Yes you’re right - seems it’s been erroring

**Comment by rarkins** [comment]
How interesting. A new build of node alpine broke it so I’ve tried rolling it back manually. Case study of why to pin Docker sha although seems like I need a way to test the docker build too

**Comment by rarkins** [comment]
Now fixed and published

**Comment by adam-moss** [comment]
Confirmed - new image pulled into environment and PR titles are no long showing {{depName}} 🎉 

Thanks for the efforts on this, greatly appreciated 🏅
